create extension if not exists pgcrypto;

-- PROFILES TABLE
create table if not exists public.profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    first_name varchar(100),
    last_name varchar(100),
    created_at timestamptz default now()
);

-- CATEGORIES TABLE
create table if not exists public.categories (
    category_id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    category_name varchar(100) not null,
    is_custom boolean default false,
    color_code varchar(7),
    created_at timestamptz default now()
);

alter table public.categories
add constraint categories_user_id_category_name_unique
unique (user_id, category_name);

-- TRANSACTIONS TABLE
create table if not exists public.transactions (
    transaction_id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    category_id bigint references public.categories(category_id) on delete set null,
    amount numeric(10,2) not null,
    description varchar(255),
    transaction_date date not null,
    created_at timestamptz default now()
);

-- INCOME TABLE
create table if not exists public.income (
    income_id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    source varchar(100),
    amount numeric(10,2) not null,
    frequency varchar(20) check (frequency in ('weekly', 'biweekly', 'monthly')),
    income_date date not null,
    created_at timestamptz default now()
);

-- SAVINGS GOALS TABLE
create table if not exists public.savings_goals (
    goal_id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    goal_name varchar(100) not null,
    target_amount numeric(10,2) not null,
    current_amount numeric(10,2) default 0,
    deadline date,
    created_at timestamptz default now()
);

-- BUDGETS TABLE
create table if not exists public.budgets (
    budget_id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    category_id bigint not null references public.categories(category_id) on delete cascade,
    monthly_limit numeric(10,2) not null,
    month int not null check (month between 1 and 12),
    year int not null check (year >= 2000),
    created_at timestamptz default now()
);

alter table public.budgets
add constraint budgets_unique_user_category_month_year
unique (user_id, category_id, month, year);

-- RECURRING TRANSACTIONS TABLE
create table if not exists public.recurring_transactions (
    recurring_id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    category_id bigint references public.categories(category_id) on delete set null,
    amount numeric(10,2) not null,
    description varchar(255),
    frequency varchar(20) check (frequency in ('daily', 'weekly', 'monthly', 'yearly')),
    next_due_date date,
    created_at timestamptz default now()
);

-- INDEXES
create index if not exists idx_categories_user_id on public.categories(user_id);
create index if not exists idx_transactions_user_id on public.transactions(user_id);
create index if not exists idx_transactions_category_id on public.transactions(category_id);
create index if not exists idx_income_user_id on public.income(user_id);
create index if not exists idx_savings_goals_user_id on public.savings_goals(user_id);
create index if not exists idx_budgets_user_id on public.budgets(user_id);
create index if not exists idx_recurring_transactions_user_id on public.recurring_transactions(user_id);

-- ROW LEVEL SECURITY (RLS)
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.transactions enable row level security;
alter table public.income enable row level security;
alter table public.savings_goals enable row level security;
alter table public.budgets enable row level security;
alter table public.recurring_transactions enable row level security;

-- RLS POLICIES
-- Each user can only access their own data

-- PROFILES
create policy "Users can view own profile"
on public.profiles
for select
using (auth.uid() = user_id);

create policy "Users can insert own profile"
on public.profiles
for insert
with check (auth.uid() = user_id);

create policy "Users can update own profile"
on public.profiles
for update
using (auth.uid() = user_id);

-- CATEGORIES
create policy "Users can view own categories"
on public.categories
for select
using (auth.uid() = user_id);

create policy "Users can insert own categories"
on public.categories
for insert
with check (auth.uid() = user_id);

create policy "Users can update own categories"
on public.categories
for update
using (auth.uid() = user_id);

create policy "Users can delete own categories"
on public.categories
for delete
using (auth.uid() = user_id);

-- TRANSACTIONS
create policy "Users can view own transactions"
on public.transactions
for select
using (auth.uid() = user_id);

create policy "Users can insert own transactions"
on public.transactions
for insert
with check (auth.uid() = user_id);

create policy "Users can update own transactions"
on public.transactions
for update
using (auth.uid() = user_id);

create policy "Users can delete own transactions"
on public.transactions
for delete
using (auth.uid() = user_id);

-- INCOME
create policy "Users can view own income"
on public.income
for select
using (auth.uid() = user_id);

create policy "Users can insert own income"
on public.income
for insert
with check (auth.uid() = user_id);

create policy "Users can update own income"
on public.income
for update
using (auth.uid() = user_id);

create policy "Users can delete own income"
on public.income
for delete
using (auth.uid() = user_id);

-- SAVINGS GOALS
create policy "Users can view own savings goals"
on public.savings_goals
for select
using (auth.uid() = user_id);

create policy "Users can insert own savings goals"
on public.savings_goals
for insert
with check (auth.uid() = user_id);

create policy "Users can update own savings goals"
on public.savings_goals
for update
using (auth.uid() = user_id);

create policy "Users can delete own savings goals"
on public.savings_goals
for delete
using (auth.uid() = user_id);

-- BUDGETS
create policy "Users can view own budgets"
on public.budgets
for select
using (auth.uid() = user_id);

create policy "Users can insert own budgets"
on public.budgets
for insert
with check (auth.uid() = user_id);

create policy "Users can update own budgets"
on public.budgets
for update
using (auth.uid() = user_id);

create policy "Users can delete own budgets"
on public.budgets
for delete
using (auth.uid() = user_id);

-- RECURRING TRANSACTIONS
create policy "Users can view own recurring transactions"
on public.recurring_transactions
for select
using (auth.uid() = user_id);

create policy "Users can insert own recurring transactions"
on public.recurring_transactions
for insert
with check (auth.uid() = user_id);

create policy "Users can update own recurring transactions"
on public.recurring_transactions
for update
using (auth.uid() = user_id);

create policy "Users can delete own recurring transactions"
on public.recurring_transactions
for delete
using (auth.uid() = user_id);